# Site
name: "DSLA Protocol Blog"
title: "Meet DSLA Protocol"
description: "A decentralized, peer-to-peer alternative to service level agreements (SLAs) on the blockchain."
logo: 'assets/img/logo.png'
favicon: 'assets/img/logo.png'
baseurl: ''
google_analytics: 'UA-74934840-3'
disqus: 'stacktical'
include: ["_pages"]
permalink: /:categories/:year/:month/:day/:title:output_ext
url: https://blog.stacktical.com

twitter:
  username: stacktical
  card: summary_large_image

# Authors
authors:
  Team:
    name: 'Team'
    display_name: 'DSLA Core Team'
    gravatar: d8c1c1b45f2fe69edac3806d574a183f
    email: 'contact@stacktical.com'
    web: https://stacktical.com
    twitter: https://twitter.com/Stacktical
    description: "The team behind DSLA Protocol, and the DSLA family of products."
  WilhemPujar:
    name: 'Wilhem Pujar'
    display_name: 'Wilhem Pujar'
    gravatar: 22dc6d7cb68c703ab7eeccf965a29034
    email: 'wilhem.pujar@stacktical.com'
    web: https://stacktical.com
    twitter: https://twitter.com/WilhemPujar
    description: "Core Developer at DSLA Protocol"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
