# Site
name: "DSLA Protocol Blog"
title: "DSLA Protocol"
description: "Welcome to the official blog of DSLA Protocol and the DSLA family of products."
logo: 'assets/img/logo.png'
favicon: 'assets/img/favicon.png'
baseurl: ''
google_analytics: 'UA-74934840-3'
disqus: 'stacktical'
include: ["_pages"]
permalink: /:categories/:year/:month/:day/:title:output_ext
url: https://blog.stacktical.com

# Authors
authors:
  Team:
    name: 'Team'
    display_name: 'DSLA Core Team'
    gravatar: d8c1c1b45f2fe69edac3806d574a183f
    email: 'contact@stacktical.com'
    web: https://stacktical.com
    twitter: https://twitter.com/Stacktical
    description: "The team behind DSLA Protocol, and the DSLA family of products."
  WilhemPujar:
    name: 'Wilhem Pujar'
    display_name: 'Wilhem Pujar'
    gravatar: 22dc6d7cb68c703ab7eeccf965a29034
    email: 'wilhem.pujar@stacktical.com'
    web: https://stacktical.com
    twitter: https://twitter.com/WilhemPujar
    description: "Core Developer at DSLA Protocol"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
